import { Brand } from '../../app/interfaces/brand';

export const brands: Brand[] = [
   
    {
        url: '/shop/category-columns-5-sidebar',
        slug: 'shopping-retail',
        name: 'Shopping & Retail',
        country: 'DE',
        image: 'assets/images/brands/brand-1.png',
    },
    {
        url: '/shop/category-columns-5-sidebar',
        slug: 'agriculture-food-beverage',
        name: 'Agriculture, Food & Beverage', 
        country: 'DE',
        image: 'assets/images/brands/brand-2.png',
    },
    {
        url: '/shop/category-columns-5-sidebar',
        slug: 'hotel-lodging-events-tourism',
        name: 'Hotel, Lodging, Events & Tourism',
        country: 'DE',
        image: 'assets/images/brands/brand-3.png',
    },  
    {
        url: '/shop/category-columns-5-sidebar',
        slug: 'travel-transportation',
        name: 'Travel & Transportation',
        country: 'DE',
        image: 'assets/images/brands/brand-4.png',
    },  
    {
        url: '/shop/category-columns-5-sidebar',
        slug: 'cargo–transport-logistics',
        name: 'Cargo – Transport, Logistics & Home Movers',
        country: 'DE',
        image: 'assets/images/brands/brand-5.png',
    },
    {
        url: '/shop/category-columns-5-sidebar',
        slug: 'medical-services',
        name: 'Medical Services ',
        country: 'DE',
        image: 'assets/images/brands/brand-6.png',
    },
    {
        url: '/shop/category-columns-5-sidebar',
        slug: 'architecture-construction',
        name: 'Architecture & Construction',
        country: 'DE',
        image: 'assets/images/brands/brand-7.png',
    },
    {
        url: '/shop/category-columns-5-sidebar',
        slug: 'local-service',
        name: 'HOUSEHOLD STAFF,Local Service',
        country: 'DE',
        image: 'assets/images/brands/brand-8.png',
    },
    {
        url: '/shop/category-columns-5-sidebar',
        slug: 'job-hiring-vacancies',
        name: 'Job Hiring & Vacancies',
        country: 'DE',
        image: 'assets/images/brands/brand-9.png',
    },
    {
        url: '/shop/category-columns-5-sidebar',
        slug: 'education-coaching-consulting',
        name: 'Education- Coaching & Consulting ',
        country: 'DE',
        image: 'assets/images/brands/brand-10.png',
    }, 
    {
        url: '/shop/category-columns-5-sidebar',
        slug: 'fashion-beauty',
        name: 'Fashion & Beauty',
        country: 'DE',
        image: 'assets/images/brands/brand-11.png',
    }, 
    {
        url: '/shop/category-columns-5-sidebar',
        slug: 'sports-fitness-recreation',
        name: 'Sports, Fitness & Recreation',
        country: 'DE',
        image: 'assets/images/brands/brand-12.png',
    },
    {
        url: '/shop/category-columns-5-sidebar',
        slug: 'service-centers-insurance',
        name: 'Service Centers & Insurance', 
        country: 'DE',
        image: 'assets/images/brands/brand-13.png',
    },   
    {
        url: '/shop/category-columns-5-sidebar',
        slug: 'science-communications',
        name: 'Science, Technology, Engineering & Communications',
        country: 'DE',
        image: 'assets/images/brands/brand-14.png',
    },
    {
        url: '/shop/category-columns-5-sidebar',
        slug: 'finance-commercial-industrial',
        name: 'Finance, Commercial & Industrial',
        country: 'DE',
        image: 'assets/images/brands/brand-15.png',
    }, 
    {
        url: '/shop/category-columns-5-sidebar',
        slug: 'media-advertising-marketing',
        name: 'Media , Real Estate, Advertising & Marketing',
        country: 'DE',
        image: 'assets/images/brands/brand-16.png',
    },
    
];
